AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Template for CF and SAM with Service Catalog
Parameters:
  Name:
    Description: The name of the bucket
    Type: String
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Name
